# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='pic',
            field=models.ImageField(upload_to='static/pictures/pics'),
        ),
    ]
